version: 2.1
orbs:
  nx: nrwl/nx@1.1.3
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  main:
    docker:
      - image: 'cimg/node:16.13.2-browsers'
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: npm install
      - nx/set-shas
      - run: npx nx affected --base=$NX_BASE --target=build --parallel=3
      - run: npx nx affected --base=$NX_BASE --target=lint --parallel=2
      - run: npx nx affected --base=$NX_BASE --target=test --parallel=2
      - run: sudo npm install -g @lhci/cli@0.8.x
      - run: lhci autorun
  pr:
    docker:
      - image: 'cimg/node:16.13.2-browsers'
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: google-chrome --version
      - run: npm install
      - nx/set-shas
      - run: npx nx affected --all --target=build --parallel=3
      - run: npx nx affected --base=$NX_BASE --target=lint --parallel=2
      - run: npx nx affected --base=$NX_BASE --target=test --parallel=2
      - run: sudo npm install -g @lhci/cli@0.8.x
      - run: lhci autorun
workflows:
  build:
    jobs:
      - main:
          filters:
            branches:
              only: main
      - pr:
          filters:
            branches:
              ignore: main
